---
# Services
enable_fan_setup: true
enable_firewall: true
enable_nginx: true
enable_portainer: true
enable_pihole: true
enable_ism: false
enable_prometheus: true
enable_monitoring: true
enable_grafana: true
enable_vpn: true
enable_internet: true
enable_uptime: true
enable_wakatime: true

# Global settings
home_pi_dir: /home/user
ansible_user: user
secondary_dns: 1.1.1.1

# Domain settings
domain_name: pi.hole
grafana_domain: grafana
portainer_domain: portainer
pihole_domain: pihole
ism_domain: ism
uptime_domain: uptime

# SSL
ssl_certificate_filename: cert-full.pem
ssl_certificate_key_filename: cert-key.pem

# Fan
fan_pin: 18
fan_temp: 55000

# Firewall
allow_list:
  - port: 22
    proto: tcp
  - port: 80
    proto: tcp
  - port: 53
    proto: tcp
  - port: 53
    proto: udp
  - port: 123
    proto: udp
  - port: 443
    proto: tcp
  - port: 2693
    proto: tcp
  - port: 5000
    proto: tcp
  - port: 8000
    proto: tcp
  - port: 9000
    proto: tcp

# Pihole
pihole_timezone: Europe/Warsaw
pihole_password: password

# ISM
ism_secret_key: random-auth-key
ism_username: user
ism_password: password
ism_nas_mac: ff:ff:ff:ff:ff:ff
ism_timezone: Europe/Warsaw

# Grafana
grafana_admin_password: password

# VPN
vpn_template: tailscale # select witch service you want to use
tailscale_key: tskey-auth-XXXXX
tailscale_network: 192.168.0.0/24
twingate_access_token: acccess-token
twingate_refresh_token: refresh-token

# Internet
internet_speedtest_interval: 60m

# Wakatime
wakatime_api_key: waka_XXXXXX