---
- name: Create Internet folder.
  ansible.builtin.file:
    path: "{{ home_pi_dir }}/internet"
    state: directory
    mode: 0755
  become: false
  register: internet_dir

- name: Copy Internet docker-compose template to Pi.
  ansible.builtin.template:
    src: templates/internet.yaml.j2
    dest: "{{ internet_dir.path }}/docker-compose.yaml"
    mode: 0640
  become: false
  notify: Restart internet

- name: Ensure Internet is running.
  community.docker.docker_compose_v2:
    project_src: "{{ internet_dir.path }}/"
