---
- name: Create Monitoring folder.
  ansible.builtin.file:
    path: "{{ home_pi_dir }}/monitoring"
    state: directory
    mode: 0755
  become: false
  register: monitoring_dir

- name: Copy Monitoring docker-compose template to Pi.
  ansible.builtin.template:
    src: templates/monitoring.yaml.j2
    dest: "{{ monitoring_dir.path }}/docker-compose.yaml"
    mode: 0640
  become: false
  notify: Restart monitoring

- name: Ensure Monitoring is running.
  community.docker.docker_compose:
    project_src: "{{ monitoring_dir.path }}/"
    build: false
  become: false
