---
- name: Create Nginx folder on Pi.
  ansible.builtin.file:
    path: "{{ home_pi_dir }}/nginx"
    state: directory
    mode: 0755
  become: false
  register: nginx_dir

- name: Create Nginx config folder on Pi.
  ansible.builtin.file:
    path: "{{ nginx_dir.path }}/config"
    state: directory
    mode: 0755
  become: false
  register: nginx_config_dir

- name: Copy Nginx config to Pi.
  ansible.builtin.template:
    src: templates/nginx.yaml.j2
    dest: "{{ nginx_dir.path }}/docker-compose.yaml"
    mode: 0640
  become: false
  notify: Restart nginx

- name: Copy Nginx docker-compose template to Pi.
  ansible.builtin.template:
    src: templates/nginx/{{ item }}.j2
    dest: "{{ nginx_config_dir.path }}/{{ item }}"
    mode: 0640
  loop:
    - grafana.conf
    - pihole.conf
    - portainer.conf
    - ism.conf
    - uptime.conf
  become: false
  notify: Restart nginx

- name: Copy Nginx certificates.
  ansible.builtin.copy:
    src: ssl
    dest: "{{ nginx_dir.path }}"
    directory_mode: true
    mode: 0640
  become: true
  notify: Restart nginx

- name: Ensure Nginx is running.
  community.docker.docker_compose:
    project_src: "{{ nginx_dir.path }}/"
    build: false
  become: false
