---
- name: Create Portainer folder.
  ansible.builtin.file:
    path: "{{ home_pi_dir }}/portainer"
    state: directory
    mode: 0755
  become: false
  register: portainer_dir

- name: Copy Portainer docker-compose template to Pi.
  ansible.builtin.template:
    src: templates/portainer.yaml.j2
    dest: "{{ portainer_dir.path }}/docker-compose.yaml"
    mode: 0640
  become: false
  notify: Restart portainer

- name: Ensure Portainer is running.
  community.docker.docker_compose:
    project_src: "{{ portainer_dir.path }}/"
    build: false
  become: false
