---
- name: Create Wakatime folder.
  ansible.builtin.file:
    path: "{{ home_pi_dir }}/wakatime"
    state: directory
    mode: 0755
  become: false
  register: wakatime_dir

- name: Copy Wakatime docker-compose template to Pi.
  ansible.builtin.template:
    src: templates/wakatime.yaml.j2
    dest: "{{ wakatime_dir.path }}/docker-compose.yaml"
    mode: 0640
  become: false
  notify: Restart wakatime

- name: Ensure Wakatime is running.
  community.docker.docker_compose_v2:
    project_src: "{{ wakatime_dir.path }}/"
