{
 "title": "ISM",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Status",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "connection{connection=\"disconnected\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "health{health=\"error\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "voltage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Temerature Inside/Outside",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "temp_out", "legendFormat": "__auto" },
    { "expr": "temp_in", "legendFormat": "__auto" }
   ]
  }
 ]
}