{
 "title": "Wakatime",
 "description": "Displays statistics from the Prometheus wakatime_exporter v0.1.0",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "top10lang",
    "query": "query_result(topk(10, sum without (instance,job) (increase(wakatime_language_seconds_total{name!=\"Other\"}[$__range])) > 0))"
   },
   { "name": "longterm", "label": "Long Term Interval", "query": "1d,7d,14d,30d,60d,120d" }
  ]
 },
 "panels": [
  {
   "title": "Time Logged",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (instance) (wakatime_cumulative_seconds_total)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Time by OS",
   "type": "graph",
   "gridPos": { "h": 10, "w": 4, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum without (instance) (increase(wakatime_operating_system_seconds_total[$__range])) > 0",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Time by Machine",
   "type": "graph",
   "gridPos": { "h": 10, "w": 5, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum without (instance) (increase(wakatime_machine_seconds_total[$__range])) > 0",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Language Distribution",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum without (instance) (increase(wakatime_language_seconds_total{name!=\"Other\"}[$__range])) > 0)",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "sum(increase(wakatime_language_seconds_total{name!~\"$top10lang\"}[$__range])) > 0",
     "legendFormat": "Other"
    }
   ]
  },
  {
   "title": "Current Rank",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (instance) (wakatime_rank)"
    }
   ]
  },
  {
   "title": "Time by Language",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum without (instance) (increase(wakatime_language_seconds_total[1d]))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Time by Project",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum without (instance) (increase(wakatime_project_seconds_total[1d]))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Total Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum without (instance) (increase(wakatime_seconds_total[1d]))",
     "legendFormat": "time"
    },
    {
     "expr": "sum without (instance) (increase(wakatime_seconds_total[$__interval]))",
     "legendFormat": "activity"
    }
   ]
  },
  {
   "title": "Daily Goal Progress",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wakatime_goal_progress_seconds_total{delta=\"day\"} / wakatime_goal_seconds{delta=\"day\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Weekly Goal Progress",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 23 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wakatime_goal_progress_seconds_total{delta=\"week\"} / wakatime_goal_seconds{delta=\"week\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  }
 ]
}