---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Top:
  - Temps:
      widget:
        type: prometheusmetric
        url: http://prometheus:9090
        refreshInterval: 10000 
        metrics:
          - label: Inside
            query: temp_in
            format:
              type: number
              suffix: °C
              options:
                maximumFractionDigits: 2
          - label: Outside
            query: temp_out
            format:
              type: number
              suffix: °C
              options:
                maximumFractionDigits: 2
  - Internet:
      widget:
        type: prometheusmetric
        url: http://prometheus:9090
        refreshInterval: 10000 
        metrics:
          - label: Down
            query: last_over_time(speedtest_download_bits_per_second[2h])
            format:
              type: bitrate
          - label: Up
            query: last_over_time(speedtest_upload_bits_per_second[2h])
            format:
              type: bitrate
- HomePi:
  - Grafana:
      icon: sh-grafana
      href: https://grafana.pi.hole
  - Portainer:
      icon: sh-portainer
      href: https://portainer.pi.hole
  - ISM:
      icon: sh-esphome
      href: https://ism.pi.hole
  - PiHole:
      icon: sh-pi-hole
      href: https://pihole.pi.hole/admin
  
- NAS:
  - Admin:
      icon: sh-truenas-scale
      href: https://nas.pi.hole
      ping: 192.168.1.102
  # - Prism:
  #     icon: sh-photoprism
  #     href: https://prism.nas.pi.hole
  - Immich:
      icon: sh-immich
      href: https://immich.nas.pi.hole
  - MeTube:
      icon: sh-metube
      href: https://metube.nas.pi.hole
  - Kasm:
      icon: sh-kasm-workspaces
      href: https://kasm.nas.pi.hole
